spring:
  datasource:
    url: jdbc:h2:mem:db?serverTimezone=Asia/Seoul;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # JPA Setting
    show_sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true
  sql: # SQL init
    init:
      mode: never

logging:
  level:
    org:
      hibernate:
        type: trace

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 500 # 500 Byte 미만일 시 압축을 적용하지 않음
  servlet:
    session:
      cookie:
        http-only: true
  multipart:
    max-file-size: 10MB # 파일 업로드의 최대 크기를 10MB로 제한
    max-request-size: 10MB


# Google OAuth
cors:
  allow-origin:
    urls: http://localhost:8080, http://localhost:3000, http://localhost:3000/google-callback

oauth:
  google:
    client-id: 399248394633-9rauhsoftsh2po6vsk01r55toncv36al.apps.googleusercontent.com
    client-secret: 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
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
    token-uri: https://oauth2.googleapis.com/token
    access-type: offline

security:
  jwt:
    token:
      secret-key: hibit@dPtnfwjstlghlaocldtjqltm796dhuasdabsdkSs2n42dbashdyasdbav2Clvyx9vsnasd
      access:
        expire-length : 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일